
export const GET_SPACE_DETAIL = 'GET_SPACE_DETAIL'
export const UPDATE_SPACE_DETAIL = 'UPDATE_SPACE_DETAIL'
export const UPDATE_SPACE_USER = 'UPDATE_SPACE_USER'
export const CLEAR_SPACE_DETAIL = 'CLEAR_SPACE_DETAIL'
export const SET_CROPPER_IMAGE_DATA = 'SET_CROPPER_IMAGE_DATA'
export const RESET_CROPPER_IMAGE_DATA = 'RESET_CROPPER_IMAGE_DATA'
export const DETAIL_SHOW_TAB = 'DETAIL_SHOW_TAB'
