export const UPDATE_USER = 'UPDATE_USER'
export const TOKEN_EXPIRE = 'TOKEN_EXPIRE'
export const SET_USER_SETTING = 'SET_USER_SETTING'
export const GET_USER_SETTING = 'GET_USER_SETTING'
export const UPDATE_REQUEST_PARAMS = 'UPDATE_REQUEST_PARAMS'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_MERCHANT = 'UPDATE_MERCHANT'
export const UPDATE_MERCHANT_NAME = 'UPDATE_MERCHANT_NAME'
export const UPDATE_LOCAL_TOKEN = 'UPDATE_LOCAL_TOKEN'



